name: Lint

on: [push]

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache Bun dependencies
        uses: actions/cache@v6
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('package.json', 'bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Node.js dependencies
        run: bun install --frozen-lockfile

      - name: Check formatting with prettier
        run: bun run check:ci

      - name: Check prisma format
        run: bunx prisma format --check

  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache Bun dependencies
        uses: actions/cache@v6
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('package.json', 'bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bunx eslint . --cache
